apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/pre-sleep: "kubectl get pods"
    dev.okteto.com/post-sleep: "kubectl get deployment"
    dev.okteto.com/post-wake: "kubectl get all"
    dev.okteto.com/pre-wake: "kubectl get secret"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: okteto/go-getting-started:hello-world
        name: hello-world
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
  - name: "hello-world"
    port: 8080
  selector:
    app: hello-world

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/generate-host: hello-world
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
