apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      # hostNetwork: true
      # hostPID: true
      # hostIPC: true
      # volumes:
      # - name: test-volume
      #   hostPath:
      #     path: /data
      # - name: test-volume2
      #   hostPath:
      #     path: /var/okteto/bin
      # - name: test-volume3
      #   hostPath:
      #     path: /ble
      # - name: test-not-allowed
      #   storageOS: 
      #     volumeName: testing
      #     readOnly: true
      containers:
      - image: mnevadom/golangregistry:1
        # resources:
        #   requests:
        #     memory: "2Gi"
        #     cpu: "4"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "4"
        name: hello-world
        # securityContext:
          # allowPrivilegeEscalation: true
          # privileged: true
          # capabilities:
            # add: ["NET_ADMIN", "SYS_TIME"]
            # add: ["SYS_PTRACE", "SETPCAP", "AUDIT_WRITE"]        
        #     drop: ["NET_ADMIN", "SYS_TIME"]

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
  - name: "hello-world"
    port: 8080
  selector:
    app: hello-world

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/generate-host: hello-world
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
