
on: [push]

name: deploy-preview

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_PATOKEN }}

    - name: "Deploy the preview environment"
      uses: okteto/deploy-preview@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: dev-previews-lucamilan