on:
  pull_request:
    branches:
      - master

name: deploy

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_PATOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          name: lucamilan

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: pr-${{ github.event.number }}
          timeout: 8m
          skipIfExists: true
